env:
  ISOLATED: "true"
  MINE: "YOURS"
before_script:
  - echo before_script
  - hostname
script:
  - echo script
  - invalid_command
  - whoami
after_script:
  - echo after_script
  - ping -c 7 127.0.0.1
