version: '3.7'
services:
  container:
    image: dinutac/estuary-discovery:4.0.8
    environment:
      EUREKA_SERVER: "{{eureka_server}}"
      APP_IP_PORT: "{{app_ip_port}}/docker/container/{{deployment_id}}"
    expose:
      - "8080"
