version: '3.7'
services:
  container:
    image: estuaryoss/discovery:4.2.2
    environment:
      EUREKA_SERVER: "{{eureka_server}}"
      APP_IP_PORT: "{{app_ip_port}}/docker/container/{{deployment_id}}"
      HTTP_AUTH_TOKEN: None
    expose:
      - "8080"
